<?php
/**
 * @file
 *
 * tag_user module file
 */

/**
 * Implements hook_user_tagable_widgets().
 *
 * @return array
 */
function tag_user_user_tagable_widgets() {
  return array(
    'text_textfield',
    'text_textarea',
    'text_textarea_with_summary',
  );
}

/**
 * Implements hook_field_widget_info_alter().
 *
 * @param $info
 */
function tag_user_field_widget_info_alter(&$info) {
  foreach (module_invoke_all('user_tagable_widgets') as $widget) {
    $info[$widget]['label'] .= " (with user tagging)";
  }
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * @param $element
 * @param $form_state
 * @param $context
 */
function tag_user_field_widget_form_alter(&$element, &$form_state, $context) {
//function tag_user_field_widget_properties_alter(&$widget, $context) {
  $widgets = module_invoke_all('user_tagable_widgets');
  if (in_array($context['instance']['widget']['type'], $widgets)) {
    $element['#default_value'] = 'hi';
    // Add the autocomplete library to steal its functions
    drupal_add_library('system', 'drupal.autocomplete');
    $element['#attached']['js'] = array(
      drupal_get_path('module', 'tag_user') . '/tag_user.js',
      array(
        'type' => 'setting',
        'data' => array('tag_user' => array('tagging' => FALSE, 'tagged_user' => '')),
      ),
    );
    $element['#tag_user_enabled'] = TRUE;
    $element['#attributes']['id'][] = 'tag-user';
    $element['#attributes']['class'][] = 'form-autocomplete';


    // TODO Add in our own theme function so we don't have to do a suffix
    // But we'd have to pretty much copy core's implementation and plug it in.
    // $element['#theme'] = 'tag_user_widget';
    //$element['#field_suffix'] = '<input' . drupal_attributes($attributes) . ' />';

    $element['#post_render'] = array('tag_user_append_autocomplete');
    //$element['#theme_wrappers'] = array('tag_user_append_autocomplete');
  }
}


function tag_user_append_autocomplete($content, $element) {
  if ($element['#type'] != 'text_format') {
    $attributes = array();
    $attributes['type'] = 'hidden';
    $attributes['id'] = 'tag-user-autocomplete';
    // TODO be careful here with subdomains and url()
    $attributes['value'] = url('user/autocomplete', array('absolute' => TRUE));
    $attributes['disabled'] = 'disabled';
    $attributes['class'][] = 'tag-user';
    $content .= '<input' . drupal_attributes($attributes) . ' />';
  }
  return ($content);
}